### ISSUE TITLE
Servers with HTTP Basic Authentication cannot be set up anymore

### ISSUE THREAD

**Issue by aaronk6** [einsteinx2/libSub#2]
* Have a Subsonic server with HTTP Basic Authentication enabled (e.g. by using an nginx proxy)
* Download a fresh copy of iSub from the App Store (so you have no existing servers configured)
* Try to setup the server

**Result:** It will fail with `"Error code 1: This is not a Subsonic server".`

**Workaround:** Disable HTTP Basic Auth on the server, configure the server in iSub, turn HTTP Basic Auth back on.

I'm using iSub version 109. This was working in earlier versions.

**Comment by einsteinx2** [comment]
Thanks for the report. Can you send a private Facebook message to the iSub page with login details to the server you're testing with? I don't have a test server handy with that kind of setup.

**Comment by aaronk6** [comment]
Sure, but I'd prefer email as I'm not a Facebook fan. Ok?

**Comment by einsteinx2** [comment]
I just didn't want to post my email publicly...

In this case, I guess just send the details to the now defunct support@isubapp.com and I'll check it (caveat to future readers, this email address is no longer monitored).

**Comment by aaronk6** [comment]
Alright! I sent them there. Thanks!

**Comment by einsteinx2** [comment]
I just tried using your test server and I'm not able to reproduce this issue. 

And after I enabled basic authentication in settings (it's in the General section at the top of iSub's settings) and used the https in the URL, it connected fine using the latest code (same as App Store version).

Are you sure you have "Enable Basic Authentication" turned on in iSub's settings? If you do, try toggling it off then on again to see if that makes any difference.

Basic auth is not enabled by default because IIRC it caused some issues with connecting to non-basic auth servers, and since it's a niche use case, I turned it off by default.

**Comment by aaronk6** [comment]
Thanks for looking into this! Problem is that you cannot go to the settings page when server is configured yet. I can provide more details tomorrow!

Cheers!

-- 
Von unterwegs gesendet

**Comment by einsteinx2** [comment]
Actually you can! On a new install, when you hit settings, the server selection screen will pop up. If you hit cancel at the bottom, you'll be back at the server list where you can hit Settings at the top. Not ideal though I agree.

Now that I think about it, the toggle should be on the server entry screen, and should be server specific, rather than device-wide. That way you can choose it when setting up the server easily. I'll make that change.

**Comment by einsteinx2** [comment]
Actually even better, you shouldn't even need to set that setting. I'll have it automatically retry using basic auth when unable to connect, and set the setting automagically.

**Comment by aaronk6** [comment]
> On a new install, when you hit settings, the server selection screen will pop up. If you hit cancel at the bottom, you'll be back at the server list where you can hit Settings at the top. Not ideal though I agree.

Not sure if I overlook something but this doesn’t work for me. It automatically brings up the login view again and again before I can tap on the “Settings” tab:

![isub_server_setup](https://cloud.githubusercontent.com/assets/446063/7399593/2b9006b6-eeb7-11e4-861c-29af58b5fe03.gif)

> Actually even better, you shouldn't even need to set that setting. I'll have it automatically retry using basic auth when unable to connect, and set the setting automagically.

That would be awesome! Again, thanks for looking into this—I know it’s an edge case. So I’d love to buy you a coffee or a beer, Bitcoin maybe? ;-)
